name: Run Integration Tests

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup up java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name : Verify java version
        run : java -version
        
      - name : Verify maven version
        run : mvn -version

      - name : Install MySql
        run : |
          sudo apt-get update
          sudo apt-get install mysql-server -y

      - name : Start MySql
        run : sudo service mysql start


      - name : Create Database
        run : mysql --user=root --password=root -e "CREATE DATABASE IF NOT EXISTS cloud_computing_project;"

      - name : Check Sql status
        run : |
          mysql --version
          sudo service mysql status


      - name : Build with Maven
        run : mvn clean install -B



      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports
